# The Docker image that will be used to build your app
image: python:3.12-slim

variables:
  QUARTO_VERSION: "1.4.554"
  PROD_DEPLOY_URL: "https://garden.errbufferoverfl.me"

cache:
  paths:
    - .cache/pip

# Functions that should be executed before the build script is run
before_script:
  - apt-get update && apt-get install -y wget ca-certificates
  - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb" -O quarto.deb
  - dpkg -i quarto.deb
  - rm quarto.deb
  - python3 -m pip install --upgrade pip
  - pip install beautifulsoup4==4.12.0

build:
  stage: build
  script:
    - quarto render . --output-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  script:
    - echo "Deploying to Production Environment at $PROD_DEPLOY_URL"
  environment:
    name: production
    url: $PROD_DEPLOY_URL
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - build
