name: Build & Deploy garden.errbufferoverfl.me

on:
  push:
    branches:
      - hugo

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.20
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

  deploy_www:
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - name: Deploy to www
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ contains(github.event.head_commit.message, 'www') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: garden.errbufferoverfl.me

  deploy_ipfs:
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - name: Publish to IPFS
        uses: hyphacoop/actions-distributed-press@v1.1
        if: ${{ contains(github.event.head_commit.message, 'ipfs') }}
        with:
          publish_dir: ./public
          dp_url: https://press.errbufferoverfl.me
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          site_url: garden.ipfs.errbufferoverfl.me
          deploy_http: false
          deploy_hyper: false
          deploy_ipfs: true

  deploy_hyper:
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - name: Publish to Hyper
        uses: hyphacoop/actions-distributed-press@v1.1
        if: ${{ contains(github.event.head_commit.message, 'hyper') }}
        with:
          publish_dir: ./public
          dp_url: https://press.errbufferoverfl.me
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          site_url: garden.hyper.errbufferoverfl.me
          deploy_http: false
          deploy_hyper: true
          deploy_ipfs: false
