name: Deploy to Distributed Press

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.20
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Publish to Distributed Press
        uses: hyphacoop/actions-distributed-press@v1.1
        with:
          publish_dir: ./public
          dp_url: https://distributed.errbufferoverfl.me
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          site_url: garden.errbufferoverfl.me
          deploy_http: true
          deploy_hyper: true
          deploy_ipfs: true
